### ISSUE TITLE
Have EDAlias work with eras

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#15908]
From email with Kevin Pedro

> I am currently in the process of trying to remove Castor from Phase2 configurations.

> In https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/SimGeneral/MixingModule/python/aliases_cfi.py, there is an EDAlias defined for the Castor digis. This is removed for FastSim using isChosen, which is deprecated. What is the right way to remove such an object?

>I tried a few things that didn't work:
>eras.phase2_common.toReplaceWith(simCastorDigis, None)
>eras.phase2_common.toModify(simCastorDigis, mix = None)

**Comment by Dr15Jones** [comment]
@kpedro88

**Comment by Dr15Jones** [comment]
assign core

**Comment by Dr15Jones** [comment]
Should be fixed by #15909 
@kpedro88 do you want to see if you can now make
```
eras.phase2_common.toModify(simCastorDigis, mix = None)
```
work?

**Comment by kpedro88** [comment]
@Dr15Jones I tested this in [kpedro88:BetterRemovalEDAlias](https://github.com/kpedro88/cmssw/tree/BetterRemovalEDAlias) after merging your branch. The Phase2 workflows ran fine with this change (tested with 20000.0). I also explicitly dumped the config to look at the result: the `EDAlias` object is still present, but with no `mix` parameter, it doesn't do anything.

**Comment by Dr15Jones** [comment]
Thanks!
