### ISSUE TITLE
Build CMSSW_10_6_0_pre3

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#26296]

**Comment by fabiocos** [comment]
build cmssw-tool-conf

**Comment by fabiocos** [comment]
+1

**Comment by smuzaffar** [comment]
@fabiocos , there was a bug in cms-bot and it should not have started the build for slc7_ppc64le_gcc700 as this is marked as IB_ONLY in the https://github.com/cms-sw/cms-bot/blob/master/config.map#L15
I have fixed this now and in future it should not trigger the release build for IB_ONLY entries.

**Comment by fabiocos** [comment]
@smuzaffar ok thanks for the clarification, it does not make sense to run the build if we cannot have the externals...

**Comment by fabiocos** [comment]
upload all

**Comment by fabiocos** [comment]
@smuzaffar there is a problem in gcc820 upload, but the link to the output is broken, any idea about what happened? I may move forward anyway with release notes...

**Comment by fabiocos** [comment]
if I am not mistaken, the Jenkins job for this upload shows success, even if nothing has still appeared in cvmfs

**Comment by fabiocos** [comment]
release-notes

**Comment by smuzaffar** [comment]
@fabio, gcc820 is now uploaded.

**Comment by fabiocos** [comment]
@smuzaffar thanks
