### ISSUE TITLE
Headers issues to be fixed

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#26758]
For future reference the report by @perrotta in https://github.com/cms-sw/cmssw/pull/26703#issuecomment-491574411

- [ ] Usage of obsolete CommonTools/Utils/interface/deltaPhi.h in CommonTools/Utils/interface/MasslessInvariantMass.h

- [ ] Usage of obsolete CommonTools/Utils/interface/deltaR.h in CommonTools/Utils/interface/MaxObjectPairSelector.h

- [x] Issues with DataFormats/Math/interface/AVXVec.h

- [x] Non existent PhysicsTools/Utilities/interface/Math.h included in PhysicsTools/IsolationUtils/interface/CalIsolationAlgoNoExp.h and PhysicsTools/IsolationUtils/interface/TauConeIsolationAlgo.h

- [ ] Issue with DataFormats/Candidate/interface/Candidate.h and DataFormats/Candidate/interface/VertexCompositePtrCandidate.h

- [x] CommonTools/UtilAlgos/interface/TFileDirectory.h is obsolete and to be removed

- [x] CommonTools/UtilAlgos/interface/ChargeSelector.h is obsolete and to be removed

- [x] Issue with SimG4Core/PhysicsLists/interface/G4Version.h

- [ ] Issues with OnlineDB/EcalCondDB/interface/FEConfigFgrEEStripDat.h and OnlineDB/EcalCondDB/interface/ITimeIOV.h

- [ ] PhysicsTools/Utilities/interface/Likelihood.h: PhysicsTools/Utilities/interface/Selector.h has moved to PhysicsTools/SelectorUtil

- [ ] Same in PhysicsTools/Utilities/interface/Product.h

- [ ] Issues with SimCalorimetry/CaloSimAlgos/interface/CaloVSimParameterMap.h

- [ ] Non-existent (since a while) ConvGaussZLineShape.h included in ElectroWeakAnalysis/ZMuMu/interface/ZMuTrackFunction.h

- [ ] Wrong includes in Validation/EventGenerator/interface/TauDecay_GenParticle.h

- [ ] ​CondFormats/​GeometryObjects/​interface/​GeometryFile.h should be removed, as well as all references to it in cmssw

- [ ] FastSimulation/Utilities/interface/RandomEngine.h to be removed as obsolete

- [ ] Non existent MCCandMatcher linked from PhysicsTools/HepMCCandAlgos/interface/MCTruthCompositeMatcher.h

- [ ] Non existent CondCore/DBCommon/interface/Time.h linked from CondCore/PopCon/interface/VerifyState.h

- [ ] Remove obsloete CondFormats/Calibration/interface/EfficiencyPayloads.h and all references to it

- [ ] Issues in CondFormats/SiPixelObjects/interface/SerializationManual.h

- [ ] Non existent PhysicsTools/Utilities/interface/Math.h included in PhysicsTools/IsolationUtils/interface/CalIsolationAlgoNoExp.h

- [ ] Remove usages of deprecated GenericJetfwd.h, BasicJetfwd.h, GenJetfwd.h

- [ ] Remove usages of deprecated DF/BTau/JTA

- [ ] Issues with DQMOffline/PFTau/interface/MatchCandidateBenchmark.h

- [ ] Usage of non supported classes in JetMETCorrections/Modules/interface/JetCorrectionProducer.h

- [ ] Non existent CommonTools/Utilities/interface/cutParser.h included in CommonTools/CandAlgos/interface/NamedCandCombiner.h

- [ ] Issues with CommonTools/ParticleFlow/interface/TopProjectors.h

- [ ] Issues with hysicsTools/UtilAlgos/interface/NullPostProcessor.h

- [ ] Non existent EGamma/EGammaAnalysisTools/src/PFIsolationEstimator.cc included in PhysicsTools/UtilAlgos/interface/AdHocNTupler.h

- [ ] Issues with SelectorUtils/interface/Expressions.h

- [ ] Non existent ElectronVPlusJetsIDSelectionFunctor.h included In PhysicsTools/PatUtils/interface/ElectronVPlusJetsIDSelectionFunctor.h

- [ ] Issues with RecoVertex/LinearizationPointFinders/interface/GenericLinearizationPointFinder.h

- [ ] Non existent WPlusJetsEventSelector.h used in PhysicsTools/PatExamples/interface/WPlusJetsEventSelector.h

- [ ] Issues with RecoVertex/GhostTrackFitter/interface/AnnealingGhostTrackFitter.h

- [ ] Issues with Alignment/MillePedeAlignmentAlgorithm/interface/MillePedeMonitor.h

- [ ] CondFormats/Serialization/interface/Equal.h:1:9: warning: #pragma once in main file

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmssw/pull/26641
https://github.com/cms-sw/cmssw/pull/26666
- https://github.com/cms-sw/cmssw/pull/26666
 should fix 
  - ElectroWeakAnalysis/ZMuMu/interface/*
  - PhysicsTools/HepMCCandAlgos/interface/MCTruthCompositeMatcher.h 
  - PhysicsTools/IsolationAlgos/interface/CalIsolationNoExtrapol.h
  - PhysicsTools/IsolationUtils/interface/*
  - PhysicsTools/UtilAlgos/interface/*
- https://github.com/cms-sw/cmssw/pull/26770 should fix DataFormats/Math/interface/AVXVec.h
- https://github.com/cms-sw/cmssw/pull/26663 should fix
  -  CommonTools/CandAlgos/interface/NamedCandCombiner.h
  - CommonTools/ParticleFlow/interface/TopProjectorAlgo.h
  -  CommonTools/ParticleFlow/interface/TopProjectors.h
  - CommonTools/UtilAlgos/interface/ChargeSelector.h
  - CommonTools/UtilAlgos/interface/ObjectCounter.h 
  - PhysicsTools/SelectorUtils/interface/Expressions.h
-

**Comment by smuzaffar** [comment]
Most of the header check errors are fixed now. The following PRs should fix the remaining errors [a]
https://github.com/cms-sw/cmssw/pull/26810
https://github.com/cms-sw/cmssw/pull/26809
https://github.com/cms-sw/cmssw/pull/26808
https://github.com/cms-sw/cmssw/pull/26663

[a] https://cmssdt.cern.ch/SDT/jenkins-artifacts/check_headers/CMSSW_11_0_X_2019-05-15-2300/slc7_amd64_gcc700/headers_with_error.log

CommonTools/UtilAlgos/interface/ChargeSelector.h
CommonTools/UtilAlgos/interface/ObjectCounter.h
Geometry/HcalTowerAlgo/interface/CaloGeometryDBHcal.h
Geometry/HcalTowerAlgo/interface/CaloGeometryDBCaloTower.h
Geometry/HGCalGeometry/interface/CaloGeometryDBHGCal.h
PhysicsTools/SelectorUtils/interface/Expressions.h
CommonTools/CandAlgos/interface/NamedCandCombiner.h
CommonTools/ParticleFlow/interface/TopProjectorAlgo.h
CommonTools/ParticleFlow/interface/TopProjectors.h
RecoVertex/LinearizationPointFinders/interface/GenericLinearizationPointFinder.h

**Comment by perrotta** [comment]
PR #26855 can remove the following obsolete headers, which also give rise to warnings in the header checks 

DataFormats/BTauReco/interface/JetTracksAssociation.h
DataFormats/JetReco/interface/BasicJetfwd.h
DataFormats/JetReco/interface/CaloJetfwd.h
DataFormats/JetReco/interface/GenJetfwd.h
DataFormats/JetReco/interface/GenericJetfwd.h
DataFormats/JetReco/interface/PFJetfwd.h

**Comment by fabiocos** [comment]
@smuzaffar I keep this issue open as a reminder, I will not update the initial list provided by Andrea as we have regular reports in the IB (e.g. https://cmssdt.cern.ch/SDT/jenkins-artifacts/check_headers/CMSSW_11_0_X_2019-08-08-2300/slc7_amd64_gcc700/build.log )

where I see that a number of problems are still there
