### ISSUE TITLE
expand coverage for creation of simGtExtUnprefireable in miniAOD

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#32304]
the initial version integrated in #31985 is making the simGtExtUnprefireable product available only in run2_miniAOD_UL setup.

todo: to figure out the full set of input workflows where `tcdsDigis:tcdsRecord` is available as input for the miniAOD step and apply that combined era modifier instead of the current `run2_miniAOD_UL`

@rekovic

**Comment by slava77** [comment]
assign reconstruction,l1

**Comment by cecilecaillol** [comment]
Fixed in https://github.com/cms-sw/cmssw/pull/31985

**Comment by cecilecaillol** [comment]
+l1

**Comment by jpata** [comment]
+reconstruction
- very old issue, but as I understand (based on reading the descriptions) it was finally fixed in https://github.com/cms-sw/cmssw/pull/31985

**Comment by jpata** [comment]
It was just pointed out in https://github.com/cms-sw/cmssw/issues/38890 that this issue is not solved. In fact

> Fixed in https://github.com/cms-sw/cmssw/pull/31985

violates causality, as this issue was opened to address the remaining bits from the PR. My bad for not noticing.

**Comment by jpata** [comment]
@cmsbuild please reopen

**Comment by qliphy** [comment]
assign l1

**Comment by cecilecaillol** [comment]
@jpata I think this issue is solved by https://github.com/cms-sw/cmssw/pull/39169. Can we close the issue?
