### ISSUE TITLE
[High Priority][DD4hep] Improve design of DDCMS handling of assemblies and parsing context

### ISSUE THREAD

**Issue by cvuosalo** [cms-sw/cmssw#34367]
PR #34344 implements support for Assemblies defined in XML and also makes data available to the DD4hep DB payload creation tool. Some aspects of the design could be simplified and improved. This issue is high priority and needs to be resolved promptly, though possibly in several sequential PRs.

Here are the issues to resolve.

@cvuosalo - `DDDetector` should not have `DDParsingContext`. The `DDParsingContext` is created for a `DDDetector`:
```c++
cms::DDParsingContext context(det);
```

_Originally posted by @ianna in https://github.com/cms-sw/cmssw/pull/34344#discussion_r664593227_

Issue: **Can a more elegant approach be found to pass the parsing context to the DB payload creator?**

=================================================

@cvuosalo - please, let dd4hep place it:
https://cmssdt.cern.ch/lxr/source/Geometry/EcalCommonData/plugins/dd4hep/DDEcalBarrelNewAlgo.cc#0976

_Originally posted by @ianna in https://github.com/cms-sw/cmssw/pull/34344#discussion_r664600980_

@cvuosalo - you only need to add a name to the namespace. Please, see the Ecal algorithm. Then, there is no need for extra code to handle the assemblies. dd4hep will do it for you.

_Originally posted by @ianna in https://github.com/cms-sw/cmssw/pull/34344#discussion_r664603676_

@cvuosalo - no need to check if it is an assembly as long as you let dd4hep handle it.

_Originally posted by @ianna in https://github.com/cms-sw/cmssw/pull/34344#discussion_r664605772_

Issue: **Simplify handling of assemblies**

**Comment by cvuosalo** [comment]
assign geometry

**Comment by cvuosalo** [comment]
Changes have been made to try to address concerns.
For DDDetector, the parsing context member has been removed, as has the explicit "makePayloads" parameter.

DDDetectorESProducer has been returned to its original form, with no defined parameter for payloads.

The map of volume pointers has been deleted from DDNamespace, and the code for handling assemblies and volumes has thereby been somewhat simplified. However, I could not figure out how to simplify Assembly processing any further. When the DD4hep extended geometry description in the DB is being read, which contains explicit Assembly definitions, the code has to treat Assemblies differently from plain Volumes. In my initial implementation attempt, I tried to treat Assemblies just like other Volumes, but I could not get that to work. The only way I could get Assembly processing to work was to have the code explicitly check whether a volume was actually an Assembly and treat it differently if it was.

**Comment by cvuosalo** [comment]
Issues were addressed in PR #34111, that has been merged. Further improvements will be open to discussion.

**Comment by cvuosalo** [comment]
+1

**Comment by ianna** [comment]
@cvuosalo and @civanch - IMHO this issue (e.g. all the comments requiring the code changes) has not been addressed in a proper manner. I agree, there were some changes in the code, but they did not solve the main dependency problem. The “bad” code is in CMSSW and this issue is closed.

If we don’t have time to write proper code to start with, when will we have time to re-write it?  - this is exactly why we should not rush accepting the PRs without reviewing them or ignoring the review.
