### ISSUE TITLE
[GCC 11] Warning: 'am' may be used uninitialized in epos-hnb.f

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#36468]
Log: https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_aarch64_gcc11/CMSSW_12_3_X_2021-12-10-2300/GeneratorInterface/ReggeGribovPartonMCInterface

Warning message:
```
(...)/src/GeneratorInterface/ReggeGribovPartonMCInterface/src/epos-hnb.f:6517:72:

 6517 |       xnb=(am(i)-x1)/dam+1.
      |                                                                        ^
  Warning: 'am' may be used uninitialized [-Wmaybe-uninitialized]
 (...)/src/GeneratorInterface/ReggeGribovPartonMCInterface/src/epos-hnb.f:6493:20:

 6493 |       real am(mxclu)
      |                    ^
note: 'am' declared here
```

**Comment by iarspider** [comment]
assing generators

**Comment by iarspider** [comment]
assign generators

**Comment by perrotta** [comment]
That is Fortran code, indeed,. I already looked at it when I saw that warning first, and it seems to me that not only it "may be used uninitialized", but it is actally always used as such. And the whole code seems rather messy, with a few patches already implemented in the past to tentatively fix similar issues reported by the compiler.

Instead of keeping fixing and maintaining that code forever, may I ask @cms-sw/generators-l2 if it is really used somewhere in CMSSW? And if not (as I would bet, given that the whole code can hardly run reasonably as it is now) couldn't it be just removed, together with other possible dead wood in the same area, and avoid having to spend uselessly time in the maintenance?

**Comment by SiewYan** [comment]
Hello @perrotta , In the past I fixed similar issues with Fortran code #32109.

I am not sure if is is used somewhere though, but I can remove it if needed. @agrohsje , do you happen to know the usage of these Fortran code?

**Comment by agrohsje** [comment]
hi @SiewYan, @perrotta, the code is still used. see e.g. this request:
https://cms-pdmv.cern.ch/mcm/requests?prepid=HIN-HINPbPbAutumn18GS-00049&shown=262271

**Comment by smuzaffar** [comment]
any suggestion what to do here to avoid this warning, should we just silence the warning via build flags?

**Comment by aandvalenzuela** [comment]
Hello,

Just to bring the attention to this warning that it is still present in the latest IBs ([CMSSW_13_1_X_2023-03-08-2300](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_aarch64_gcc11/CMSSW_13_1_X_2023-03-08-2300/GeneratorInterface/ReggeGribovPartonMCInterface)). Can we proceed by compiling the file with `-Wno-maybe-uninitialized`?

Thanks,
Andrea.

**Comment by Dr15Jones** [comment]
I have a pull request in with a fix #40962

**Comment by aandvalenzuela** [comment]
Thanks @Dr15Jones!
